# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsShell < Formula
  desc "AWS Shell - A CLI tool for AWS"
  homepage "https://github.com/Goodmain/aws-shell"
  version "1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.0/aws-shell_darwin_amd64.tar.gz"
      sha256 "8ba95eb041716141373265a6567da02ff2c28684af6af7cc5952b48f8044e3ef"

      define_method(:install) do
        bin.install "aws-shell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.0/aws-shell_darwin_arm64.tar.gz"
      sha256 "36f1190d612507dc82ed0c90738ffdae814072780d27e1d16026dd53415d20db"

      define_method(:install) do
        bin.install "aws-shell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.0/aws-shell_linux_amd64.tar.gz"
      sha256 "92393941dc8411e84d557584170d7e8244be8f57a6773c337a8f6dff29723200"
      define_method(:install) do
        bin.install "aws-shell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.0/aws-shell_linux_arm64.tar.gz"
      sha256 "4f594da0c17b2629b93d0b070e5070ca47fde1088a14ea9fd6ef944f9530ab39"
      define_method(:install) do
        bin.install "aws-shell"
      end
    end
  end

  test do
    system "#{bin}/aws-shell --version"
  end
end
