# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsh < Formula
  desc "AWS Shell - A CLI tool for AWS"
  homepage "https://github.com/Goodmain/aws-shell"
  version "1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.1/aws-shell_darwin_amd64.tar.gz"
      sha256 "78b305af8bc1c03d6682490c1580dcf68db13514d77af0ce7485ddacbcdfbc3b"

      define_method(:install) do
        bin.install "awsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.1/aws-shell_darwin_arm64.tar.gz"
      sha256 "b3f7cd5b5780807e97df1aa48c9a272d186814826123014c40cfd9a402d83f2f"

      define_method(:install) do
        bin.install "awsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.1/aws-shell_linux_amd64.tar.gz"
      sha256 "4d57b7e9b9442b86c7b9221bfecc628253019d5e89b456fe4bacef7bdb01278c"
      define_method(:install) do
        bin.install "awsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Goodmain/aws-shell/releases/download/v1.1/aws-shell_linux_arm64.tar.gz"
      sha256 "eb2fcfddfc4c1c21f6755f8181d861b2e2c17751adbf2bc36e06e95fd4f94f35"
      define_method(:install) do
        bin.install "awsh"
      end
    end
  end

  test do
    system "#{bin}/awsh --version"
  end
end
